export const SUBCONTRACTOR_CELL_STYLES = {
    maxWidth: 150,
    wordBreak: 'break-word',
} as React.CSSProperties;

export const CONFIGURATION_TABLE = [
    { label: 'ID', value: 'id', sortable: true },
    { label: 'Invoice Date', value: 'date', sortable: true },
    { label: 'Departments', value: 'departments' ,sortable: false},
    { label: 'Timesheet Amount', value: 'timesheets_amount', sortable: true },
    { label: 'POs', value: 'po_amount',sortable: true },
    { label: 'Paid ', value: 'paid_amount', sortable: true },
    { label: 'Billing Cycle', value: 'billing_cycle', sortable: true },
    { label: 'Job Type', value: 'job_types', sortable: true  },
    { label: 'Invoices', value: 'invoice_count', sortable: true},
    { label: 'Actions', value: 'actions', sortable: false },
];
export const INVOICES_TABLE = [
    { label: 'Invoice Date',     value: 'date', sortable: true },
    { label: 'Departments',      value: 'departments' },
    { label: 'Job Type',         value: 'job_type'  },
    { label: 'Timesheet Amount', value: 'timesheet_amount', sortable: true },
    { label: 'POs',              value: 'po',sortable: true },
    { label: 'Paid',             value: 'paid', sortable: true },
    { label: 'Regular',          value: 'regular_hours', sortable: true },
    { label: 'Overtime',         value: 'overtime_hours', sortable: true },
    { label: 'Holiday',          value: 'holiday_hours', sortable: true },
    { label: 'Total Due',        value: 'total_due', sortable: true },
    { label: '',                 value: 'actions' },
];
export const TIMESHEETS_TABLE= [
    //{ label: 'Id', value: 'invoices.id', sortable: true },
    { label: 'Start Date/Time', value: 'job_type'  },
    { label: 'End Date/Time', value: 'actions' },
    { label: 'Departments', value: 'invoices.departments' },
    { label: 'Section #', value: 'invoices.department' },
    { label: 'PO #', value: 'invoices.timesheet_amount' },
    { label: 'Billed', value: 'invoices.po',sortable: true },
    //{ label: 'Coned Ed Ticket # ', value: 'paid', sortable: true },
    { label: ' Requestor', value: 'invoices.billing_cycle' },
    { label: 'Request Time', value: 'job_type'  },
    { label: 'Supervisor', value: 'actions' },
    //{ label: 'CE Solutions ', value: 'invoices.id', sortable: true },
    //{ label: 'JOB TICKET#', value: 'invoices.date', sortable: true },
    { label: 'Location Address & Cross Street', value: 'invoices.department' },
    { label: 'Muni', value: 'invoices.timesheet_amount' },
    { label: 'Flagger  Name', value: 'invoices.po'},
    //{ label: 'Flagger Emloyee # ', value: 'paid', sortable: true },
    //{ label: 'T/S RECEIVED', value: 'invoices.billing_cycle', sortable: true },
    //{ label: '1/2 Hour Break Taken', value: 'invoices.date', sortable: true },
    //{ label: '1/2 Hour Break Taken', value: 'invoices.department' },
    //{ label: 'Total HRS Worked', value: 'invoices.timesheet_amount', sortable: true },
    { label: 'Regular Hours', value: 'invoices.po' },
    //{ label: 'OT ', value: 'paid', sortable: true },
    //{ label: 'Total Invoice Amount', value: 'invoices.billing_cycle', sortable: true },
    { label: 'Holiday Hours', value: 'job_type'  },
    //{ label: 'Date Of Service', value: 'invoices.date', sortable: true },

];
